### ISSUE TITLE
Suggestion for articles page

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/ftlabs.github.io#18]
![articlestimeline](https://cloud.githubusercontent.com/assets/913687/25549988/53316480-2c6d-11e7-9137-c85b0cbd70ca.png)

**Comment by seanmtracey** [comment]
The font weights aren't quite right at the moment, but I don't have the Origami fonts (with the various weights) to hand. I think the general structure works well though. Could also collapse easily on mobile devices.

**Comment by Lily2point0** [comment]
Looking good, just ensure each article clearly links to the associated content.
