### ISSUE TITLE
Integrate o-colors

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/ftlabs.github.io#37]
We're adding hex codes for colors in our Sass/CSS files when we could just work on integrating o-colors into our build.

**Comment by Sqyphen** [comment]
Closed - not going to implement this

**Comment by seanmtracey** [comment]
👀

**Comment by Sqyphen** [comment]
Apologies, word was given from on high 😐

**Comment by seanmtracey** [comment]
No need for apologies, just having some fun. I had no idea this was still open 😂

**Comment by Sqyphen** [comment]
Oh! 😁
